/**
 * Writes `frontend/.env.local` from the current agent run.
 *
 * Contract addresses are public testnet data and are also committed as defaults in
 * `frontend/lib/deployment.ts`. Desk AES keys are NOT committed — they land only in
 * `.env.local`, which is gitignored, so a demo can decrypt without key material entering
 * the repository.
 *
 * Run: npx ts-node scripts/frontend-config.ts
 */
import fs from "fs"
import path from "path"
import { MANDATES } from "./agents/desks"
import { readEnv } from "./utils/traders"

const ROOT = path.join(__dirname, "..")
const STATE = path.join(ROOT, "agents-state.json")
const OUT = path.join(ROOT, "frontend", ".env.local")

function main() {
  if (!fs.existsSync(STATE)) {
    throw new Error(`No agents-state.json — run "STAGE=setup npm run agents" first.`)
  }
  const state = JSON.parse(fs.readFileSync(STATE, "utf8"))
  if (!state.cross || !state.messaging) throw new Error(`State has no deployed addresses yet.`)

  const env = readEnv()
  const addresses = (env.PUBLIC_KEYS ?? "").split(",").filter(Boolean)
  const aesKeys = (env.USER_KEYS ?? "").split(",").filter(Boolean)

  const desks = MANDATES.map((m, i) => ({ name: m.name, address: addresses[i], aesKey: aesKeys[i] })).filter(
    (d) => d.address && d.aesKey,
  )

  if (desks.length !== MANDATES.length) {
    console.warn(`  warning: only ${desks.length}/${MANDATES.length} desks have both an address and an AES key`)
  }

  const body = [
    `# Generated by scripts/frontend-config.ts — do not commit.`,
    `NEXT_PUBLIC_RPC_URL=https://testnet.coti.io/rpc`,
    `NEXT_PUBLIC_CROSS=${state.cross}`,
    `NEXT_PUBLIC_MESSAGING=${state.messaging}`,
    `# Desk AES keys, for local decryption in the browser. Testnet only.`,
    `NEXT_PUBLIC_DEMO_DESKS=${JSON.stringify(desks)}`,
    ``,
  ].join("\n")

  fs.writeFileSync(OUT, body, "utf8")

  console.log(`wrote ${path.relative(ROOT, OUT)}`)
  console.log(`  cross     ${state.cross}`)
  console.log(`  messaging ${state.messaging}`)
  console.log(`  desks     ${desks.map((d) => d.name).join(", ")}`)
  console.log(`\nAlso update the committed defaults in frontend/lib/deployment.ts if this`)
  console.log(`deployment should be what visitors see by default.`)
}

main()
